kind: Service
apiVersion: v1
metadata:
  name: fastapi-service
  namespace: hvl5-cli-deployment
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: data-foundry-2023-fastapi-dev