kind: Service
apiVersion: v1
metadata:
  name: app-service
  namespace: hvl5-cli-deployment
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: data-foundry-2023-app-dev